version: "3.8"
name: "api-polygon"

services:

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1440:1433"
    environment:
      SA_PASSWORD: "Strong_p@ssword12"
      ACCEPT_EULA: "Y"
    networks:
      - my-net

  api-orders:
    build:
      context: "./"
      dockerfile: "./Orders.Api/dockerfile"
    container_name: "api-orders"
    volumes:
      - "~/.aspnet/https/:/https:ro"
    depends_on:
      - sql-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Qwerty123
    ports:
      - 5001:443
      - 5051:80
    networks:
      - my-net


networks:
  my-net:
    driver: bridge
